### ISSUE TITLE
Feature: add option to reload sources on save

### ISSUE THREAD

**Issue by arothuis** [arothuis/markdown-it-biblatex#13]
I would like to understand this problem better and improve code coverage.
It has something to do with a VS Code plug-in, but I cannot seem to reproduce it.

See #11

**Comment by ryushinn** [comment]
Hi arothuis. Thanks for you looking into this issue!

Basically, this issue came to me when I followed [this doc](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins) and wrote the vscode extension to use your plugin.

## How to reproduce
By doing these you would probably reproduce the issue:
1. install [this extension](https://github.com/ryushinn/vscode-markdown-references/releases/tag/v0.1.0) into your vscode, or choose to build from [the source](https://github.com/ryushinn/vscode-markdown-references) on your own by following [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions). This extension just injects your plugin into the vscode markdown-it engine, which is too easy to do wrong (hopefully, but please warn me if I really did wrong).
2. use the vscode and its built-in markdown preview to read one .md file

FYI, my vscode is 1.76.1. And you need to specify the .bib file in this extension's setting.

## Known issues
1. fails to preview if the 'env.bib' is not being checked.
2. if using 1.0.1 you merged (thank for it!), we would have a proper preview. But the preview fails again if we cite [@foo] and foo is not in the .bib file. What I expect is that [@foo] remains plain (not being processed) in the preview.

## BTW
I did some investigation onto this issue as well. From what I can say is that the vscode markdown-it engine seems to ignore/refresh the `env` variable. So even if we inject some external information into the `env` sandbox during parsing tokens, we connot access them again in the renderer. This results in wrong behaviors of any plugin that relies on `env`, which I confirmed with [another plugin](https://www.npmjs.com/package/markdown-it-references) implementing cross-reference.

**Comment by ryushinn** [comment]
I guess the plug-in you mentioned is referred to "vscode-markdown-references"? So do you mean "directly test markdown-it + markdown-it-biblatex" by "test without the plug-in"?

As the plug-in is the officially-suggested way to incorporate markdown-it plugins into VSCode, it is necessary to have it if we want markdown-it-biblatex when using VSCode.

**Comment by arothuis** [comment]
For posterity's sake and to prevent misunderstanding, let me elaborate. Markdown-it is independent from Visual Studio Code: it is a library to render markdown, used by a couple of other projects (most notably, [11ty](https://www.11ty.dev/)). You can add plug-ins to markdown-it to add custom syntax when rendering this, of which markdown-it-biblatex is an example.

> If it is an issue with the plug-in, it's beyond the control of this library. Perhaps we could test, report and fix it in the plug-in?

I'm referring to vscode-markdown-references. If the issue is with that plug-in (i.e. it does not rerender properly when either the Markdown-file or the bibtex-file changes), it should be fixed there. If the error occurs without vscode-markdown-references, we should fix it in our library. The way to establish this is to write a test which reproduces the issue.

The goal of markdown-it-biblatex is to make it possible to render bibliographies in markdown-it. It is not a goal to be compatible with projects that use markdown-it. Dependent projects should either use our project directly, add an adapter for compatibility and control or use another library.

**Comment by ryushinn** [comment]
Thanks for your elaboration. So you are saying that we need a test (like [those](https://github.com/arothuis/markdown-it-biblatex/tree/main/test) in this library) to reproduce "non-existent references" and locate what this issue really occurs? 

I would like to write this if you don't mind pointing me to some example codes to start.

**Comment by arothuis** [comment]
Thanks! I can help if/when I have time. Let me start you off a little bit.

We have a testing setup that works by matching input file (`.md`) and expected output file (`.html`) by name.
These files can be found under `tests/fixtures`. 

You can give these files to the test runner by adding them in the examples array in `integration.test.js`. 
In that file, we have taken care to add named contexts (what is the area that is being testes) and named specifications (what exactly is being tested). The point is that these descriptions help developers understand what behavior is expected.

If I understand your known issue 2 correctly, we want to specify (and test) that a reference remains unprocessed if not present in bib-file, so our test name would be exactly that: `'a reference remains unprocessed if not present in bib-file'`. Now we make two files, `unprocessed-reference.md` and `unprocessed-reference.html`, which contain the input and the desired output respectively. Keep these simple, so just a line of text with a reference in it. If the test fails, we have automated our reproducible bug. If the test succeeds, we have an automated informal proof and a guard against regression.

**Comment by arothuis** [comment]
I've been thinking about the VSCode plug-in...

Keep in mind we only load the bib-file once (upon configuration of markdown-it).
A VSCode plug-in using markdown-it probably does not reconfigure when rerendering (could be quite slow).

Parsing a bib-file can also be quite slow if we do it on each render.
Perhaps we can offer an opt-in: `reloadBibFileOnRender` (reload if `env.bib` is not set), but I'm not sure if this is a good idea, if this solves anything or how to properly test it.

**Comment by arothuis** [comment]
Is this still a desired feature?

If I remember correctly this is the issue:
1. Currently, the files for bibliography, style and locale are loaded during markdown plugin initialization
2. My assumption is that markdown plugins are not reloaded on every change in the vscode plugin
3. This results in changes in aforementioned files not being picked up in the preview

My proposed fix would entail:
1. Add a configuration flag `reloadFilesOnEveryRender`
2. In the renderer, add a condition for this flag, read out the configured files and re-import them

This can presumably be tested automatically by (re)writing the bib file during the test and asserting results are as expected.
